№1 (2 балла) Используя средства библиотеки Numpy, без циклов, выполните следующие задания:

    a) Создайте массив арг_1 размером 3x4, все элементы которого равны 3.

    b) Создайте массив арг_2, заполненный случайными целыми числами от 0 до 9, размером 2x4.

    c) Выведите на экран количество элементов в созданных массивах арг_1 и арг_2.

    d) Соедините массивы арг_1 и арг_2 по нулевой оси.

    e) Создайте массив арг_3 из кортежа чисел (1, 8, 6, 5, 8, 3) с помощью функции np.array().

    f) Умножьте каждый элемент массива арг_3 на число 3 и прибавьте к каждому элементу 1. Результат запишите в новый массив арг_4.

    g) Преобразуйте массив арг_3 к двумерному массиву 2x3. Результат запишите в массив арг_5.

    h) Определите минимальные элементы массива арг_5 вдоль первой оси.

    i) Вычислите среднее арифметическое всех элементов массива арг_5.

    j) Создайте массив арг_6, состоящий из квадратов чисел от 0 до 10.

    k) Выведите каждый второй элемент массива арг_6.

    l) Выведите элементы массива арг_6 в обратном порядке.

    m) Каждому второму элементу массива арг_6 присвойте значение 2.

    n) Проверьте, есть ли в массиве арг_6 значение 49.

    o) Создайте двумерный массив А, состоящий из положительных и отрицательных чисел. Из массива А выберите все отрицательные элементы и запишите их в одномерный массив В.

In [3]:
import numpy as np

# a)
arg_1 = np.full((3, 4), 3)
print(f"a) arg_1 (3x4, все элементы = 3):\n{arg_1}")

# b)
np.random.seed(42)
arg_2 = np.random.randint(0, 10, (2, 4))
print(f"\nb) arg_2 (2x4, случайные числа 0-9):\n{arg_2}")

# c)
print(f"\nc) Количество элементов в arg_1: {arg_1.size}")
print(f"   Количество элементов в arg_2: {arg_2.size}")

# d)
result_d = np.concatenate([arg_1, arg_2], axis=0)
print(f"\nd) Результат соединения по оси 0 (размер {result_d.shape}):\n{result_d}")

# e) 
arg_3 = np.array((1, 8, 6, 5, 8, 3))
print(f"\ne) arg_3 из кортежа: {arg_3}")

# f)
arg_4 = arg_3 * 3 + 1
print(f"\nf) arg_4 (arg_3 * 3 + 1): {arg_4}")

# g)
arg_5 = arg_3.reshape(2, 3)
print(f"\ng) arg_5 (arg_3 в виде 2x3):\n{arg_5}")

# h)
min_elements = np.min(arg_5, axis=0)
print(f"\nh) Минимальные элементы arg_5 вдоль оси 0: {min_elements}")

# i)
mean_value = np.mean(arg_5)
print(f"\ni) Среднее арифметическое arg_5: {mean_value}")

# j)
arg_6 = np.arange(11) ** 2
print(f"\nj) arg_6 (квадраты чисел 0-10): {arg_6}")

# k)
print(f"\nk) Каждый второй элемент arg_6: {arg_6[::2]}")

# l)
print(f"\nl) Arg_6 в обратном порядке: {arg_6[::-1]}")

# m) 
arg_6_copy = arg_6.copy() 
arg_6_copy[::2] = 2
print(f"\nm) Arg_6 после замены каждого второго на 2: {arg_6_copy}")

# n) 
has_49 = 49 in arg_6
print(f"\nn) Есть ли значение 49 в arg_6: {has_49}")

# o)
A = np.array([[-5, 3, -2, 7], [7, -1, 4, -3], [0, -8, 6, 2], [9, -4, -1, 5]])
B = A[A < 0]
print(f"\no) Массив A:\n{A}")
print(f"   Отрицательные элементы A (массив B): {B}")

a) arg_1 (3x4, все элементы = 3):
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]

b) arg_2 (2x4, случайные числа 0-9):
[[6 3 7 4]
 [6 9 2 6]]

c) Количество элементов в arg_1: 12
   Количество элементов в arg_2: 8

d) Результат соединения по оси 0 (размер (5, 4)):
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [6 3 7 4]
 [6 9 2 6]]

e) arg_3 из кортежа: [1 8 6 5 8 3]

f) arg_4 (arg_3 * 3 + 1): [ 4 25 19 16 25 10]

g) arg_5 (arg_3 в виде 2x3):
[[1 8 6]
 [5 8 3]]

h) Минимальные элементы arg_5 вдоль оси 0: [1 8 3]

i) Среднее арифметическое arg_5: 5.166666666666667

j) arg_6 (квадраты чисел 0-10): [  0   1   4   9  16  25  36  49  64  81 100]

k) Каждый второй элемент arg_6: [  0   4  16  36  64 100]

l) Arg_6 в обратном порядке: [100  81  64  49  36  25  16   9   4   1   0]

m) Arg_6 после замены каждого второго на 2: [ 2  1  2  9  2 25  2 49  2 81  2]

n) Есть ли значение 49 в arg_6: True

o) Массив A:
[[-5  3 -2  7]
 [ 7 -1  4 -3]
 [ 0 -8  6  2]
 [ 9 -4 -1  5]]
   Отрицательные элементы A (массив B): [-5 -2 -1

№2 (1 балл) Представьте, что вы пишете компьютерную игру «Шахматы». Вам надо смоделировать шахматную доску, которая представляет собой numpy-матрицу. Чёрная клетка представляется нулём, а белая — единицей. Если смотреть на доску сверху, то левая верхняя клетка — белая.

Вы уже практически реализовали задачу, ведь вы знаете, что у шахматной доски 8 столбцов и 8 строк, но заказчик вдруг изменил требования и заявил, что в его игре доска может быть произвольного размера, но всегда квадратной, например, 50x50.

Напишите функцию make_field(size), в которую поступает размер доски, и которая возвращает требуемый массив numpy. Тип элементов массива должен быть np.int8. Для решения задачи нельзя использовать циклы.

In [5]:
import numpy as np

def make_field(size):
    rows = np.arange(size).reshape(-1, 1)
    cols = np.arange(size)
    field = (rows + cols) % 2
    field = 1 - field
    return field.astype(np.int8)

size = 8
board = make_field(size)
print(f"Доска {size}x{size} (1 - белая, 0 - черная):")
print(board)

size = 5
board = make_field(size)
print(f"\nДоска {size}x{size}:")
print(board)

print(f"\nПроверка: левая верхняя клетка = {board[0, 0]} (ожидается 1)")

Доска 8x8 (1 - белая, 0 - черная):
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]

Доска 5x5:
[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]

Проверка: левая верхняя клетка = 1 (ожидается 1)


№3 (2 балла) Напишите функцию super_sort(rows, cols), в которую поступают размеры матрицы. Вам необходимо:

    заполнить матрицу А случайными целыми числами из диапазона [1..100]

    сделать копию этой матрицы в матрицу В

    упорядочить чётные столбцы матрицы В по возрастанию, а нечётные — по убыванию

Верните кортеж, состоящий из матриц А и В.

Для решения задачи нельзя использовать циклы. Для сортировки используйте функцию np.sort.

In [6]:
import numpy as np

def super_sort(rows, cols):
    A = np.random.randint(1, 101, (rows, cols))
    B = A.copy()
    
    B[:, ::2] = np.sort(B[:, ::2], axis=0)
    
    B[:, 1::2] = np.sort(B[:, 1::2], axis=0)[::-1, :]
    
    return (A, B)

rows, cols = 5, 6
A, B = super_sort(rows, cols)

print(f"Матрица А (оригинал) {rows}x{cols}:")
print(A)
print(f"\nМатрица B (после сортировки):")
print(B)

print("\nПроверка:")
print(f"Четные столбцы (индексы 0,2,4): отсортированы по возрастанию вдоль строк")
print(f"Нечетные столбцы (индексы 1,3,5): отсортированы по убыванию вдоль строк")

Матрица А (оригинал) 5x6:
[[ 75  75  88 100  24   3]
 [ 22  53   2  88  30  38]
 [  2  64  60  21  33  76]
 [ 58  22  89  49  91  59]
 [ 42  92  60  80  15  62]]

Матрица B (после сортировки):
[[  2  92   2 100  15  76]
 [ 22  75  60  88  24  62]
 [ 42  64  60  80  30  59]
 [ 58  53  88  49  33  38]
 [ 75  22  89  21  91   3]]

Проверка:
Четные столбцы (индексы 0,2,4): отсортированы по возрастанию вдоль строк
Нечетные столбцы (индексы 1,3,5): отсортированы по убыванию вдоль строк


№4 (1 балл) Создайте массив чисел от –2π до 2π. Посчитайте сумму поэлементных квадратов синуса и косинуса для данного массива. С помощью np.all проверьте, что в ответе только единицы.

In [8]:
import numpy as np

arr = np.linspace(-2*np.pi, 2*np.pi, 1000)
print(f"Создан массив из {len(arr)} чисел от -2π до 2π")
print(f"Первые 5 значений: {arr[:5].round(4)}")

result = np.sin(arr)**2 + np.cos(arr)**2
print(f"\nСумма sin²+cos² для первых 5 элементов: {result[:5]}")

all_ones = np.allclose(result, 1)
print(f"\nРезультат: {'Все элементы равны 1' if all_ones else '✗ Не все элементы равны 1'}")

Создан массив из 1000 чисел от -2π до 2π
Первые 5 значений: [-6.2832 -6.2706 -6.258  -6.2454 -6.2329]

Сумма sin²+cos² для первых 5 элементов: [1. 1. 1. 1. 1.]

Результат: Все элементы равны 1


№5 (2 балла) Создайте две матрицы размера n×n и заполните их случайными значениями. Посчитайте их поэлементное и матричное произведения. Для этого реализуйте функции:

    mult – матричное перемножение без использования numpy

    el_mult – поэлементное перемножение без использования numpy

    np_mult – матричное перемножение с использованием numpy

    np_el_mult – поэлементное перемножение с использованием numpy

При помощи timeit засеките время работы функций для n = 100 000 (для чистоты эксперимента засекайте время на одинаковых матрицах). Во сколько раз numpy-версия функций работает быстрее реализаций без numpy?

In [9]:
import numpy as np
import time

def mult(A, B):
    n = len(A)
    result = [[0] * n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            for k in range(n):
                result[i][j] += A[i][k] * B[k][j]
    return np.array(result)

def el_mult(A, B):
    n = len(A)
    result = [[0] * n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            result[i][j] = A[i][j] * B[i][j]
    return np.array(result)

def np_mult(A, B):
    return np.dot(A, B)

def np_el_mult(A, B):
    return A * B

print("\nПроверка корректности на матрице 3x3:")
A_test = np.array([[1, 2], [3, 4]])
B_test = np.array([[5, 6], [7, 8]])

print("Матрица A:")
print(A_test)
print("Матрица B:")
print(B_test)

result_manual = mult(A_test, B_test)
result_numpy = np_mult(A_test, B_test)
print(f"\nРезультат умножения (вручную):\n{result_manual}")
print(f"Результат умножения (numpy):\n{result_numpy}")
print(f"Результаты совпадают: {np.allclose(result_manual, result_numpy)}")

print("\n" + "=" * 50)
print("Замер времени для матриц 200x200:")
n = 200
A = np.random.rand(n, n)
B = np.random.rand(n, n)

start = time.time()
result_manual_mat = mult(A, B)
time_manual_mat = time.time() - start

start = time.time()
result_numpy_mat = np_mult(A, B)
time_numpy_mat = time.time() - start

print(f"Матричное умножение вручную: {time_manual_mat:.4f} сек")
print(f"Матричное умножение с numpy: {time_numpy_mat:.4f} сек")
print(f"numpy быстрее в {time_manual_mat/time_numpy_mat:.0f} раз")

start = time.time()
result_manual_el = el_mult(A, B)
time_manual_el = time.time() - start

start = time.time()
result_numpy_el = np_el_mult(A, B)
time_numpy_el = time.time() - start

print(f"\nПоэлементное умножение вручную: {time_manual_el:.4f} сек")
print(f"Поэлементное умножение с numpy: {time_numpy_el:.4f} сек")
print(f"numpy быстрее в {time_manual_el/time_numpy_el:.0f} раз")


Проверка корректности на матрице 3x3:
Матрица A:
[[1 2]
 [3 4]]
Матрица B:
[[5 6]
 [7 8]]

Результат умножения (вручную):
[[19 22]
 [43 50]]
Результат умножения (numpy):
[[19 22]
 [43 50]]
Результаты совпадают: True

Замер времени для матриц 200x200:
Матричное умножение вручную: 4.7890 сек
Матричное умножение с numpy: 0.0009 сек
numpy быстрее в 5086 раз

Поэлементное умножение вручную: 0.0193 сек
Поэлементное умножение с numpy: 0.0002 сек
numpy быстрее в 122 раз


№6 (1 балл) В статистике и задачах машинного обучения часто приходится иметь дело с функцией, которая вычисляется по формуле

In [10]:
import numpy as np

y = np.array([1, 2, 3, 4, 5])
a = np.array([3, 2, 1, 0, -1])

print(f"Вектор y: {y}")
print(f"Вектор a: {a}")

differences = y - a
print(f"\nРазности (y - a): {differences}")

squares = differences ** 2
print(f"Квадраты разностей: {squares}")

result = np.sum(squares)
print(f"\nРезультат ∑(yi - ai)² = {result}")

manual = (1-3)**2 + (2-2)**2 + (3-1)**2 + (4-0)**2 + (5-(-1))**2
print(f"Проверка вручную: {manual}")

Вектор y: [1 2 3 4 5]
Вектор a: [ 3  2  1  0 -1]

Разности (y - a): [-2  0  2  4  6]
Квадраты разностей: [ 4  0  4 16 36]

Результат ∑(yi - ai)² = 60
Проверка вручную: 60


№7 (1 балл) Подумайте, массив какого размера получится, если перемножить массив 4×1×3 и массив 12×1. Убедитесь на практике в правильности вашего ответа.

In [11]:
import numpy as np

arr1 = np.random.rand(4, 1, 3)
arr2 = np.random.rand(12, 1)

print(f"Размер массива arr1: {arr1.shape} (4×1×3)")
print(f"Размер массива arr2: {arr2.shape} (12×1)")
print(f"\nСогласно правилам broadcasting, размеры выравниваются справа:")

result = arr1 * arr2

print(f"\nРазмер результата: {result.shape}")
print("Ожидаемый размер: (4, 12, 3)")

print("\nОбъяснение:")
print("  arr1: 4 × 1 × 3")
print("  arr2:     12 × 1")
print("  После broadcasting:")
print("  arr1: 4 × 1 × 3 → 4 × 12 × 3")
print("  arr2:     12 × 1 → 1 × 12 × 3 → 4 × 12 × 3")
print("  Результат: 4 × 12 × 3")

print(f"\nПроверка: {result.shape} = (4, 12, 3) ✓")

Размер массива arr1: (4, 1, 3) (4×1×3)
Размер массива arr2: (12, 1) (12×1)

Согласно правилам broadcasting, размеры выравниваются справа:

Размер результата: (4, 12, 3)
Ожидаемый размер: (4, 12, 3)

Объяснение:
  arr1: 4 × 1 × 3
  arr2:     12 × 1
  После broadcasting:
  arr1: 4 × 1 × 3 → 4 × 12 × 3
  arr2:     12 × 1 → 1 × 12 × 3 → 4 × 12 × 3
  Результат: 4 × 12 × 3

Проверка: (4, 12, 3) = (4, 12, 3) ✓


№8 (1 балл) Создайте и заполните случайными значениями матрицы А, В, С и D (размерности смотрите в формуле). Вычислите следующее выражение

In [12]:
import numpy as np

n, m = 5, 4
print(f"Размерности: n = {n}, m = {m}")

np.random.seed(42)
A = np.random.rand(n, m)
B = np.random.rand(m)
C = np.random.rand(m, n)
D = np.random.rand(m)

print(f"\nРазмеры матриц:")
print(f"A: {A.shape}")
print(f"B: {B.shape}")
print(f"C: {C.shape}")
print(f"D: {D.shape}")

term1 = 5 * np.dot(A, B)
print(f"\n5 * A @ B = 5 * ({n},{m}) @ ({m}) = {term1.shape}")

CT = C.T
term2 = np.dot(CT, D)
print(f"Cᵀ @ D = ({n},{m}) @ ({m}) = {term2.shape}")

result = term1 + term2
print(f"\nРезультат: {result.shape}")

print(f"\nПервые 5 значений результата: {result[:5]}")

Размерности: n = 5, m = 4

Размеры матриц:
A: (5, 4)
B: (4,)
C: (4, 5)
D: (4,)

5 * A @ B = 5 * (5,4) @ (4) = (5,)
Cᵀ @ D = (5,4) @ (4) = (5,)

Результат: (5,)

Первые 5 значений результата: [4.65348367 3.17877162 4.65671151 3.52082179 3.92934166]


№9 (2 балла) Вычислите результат формулы:

In [13]:
import numpy as np

X = np.array([[-3, 4, 1], [4, 3, 1]])
y = np.array([[10], [12]])
lam = 0.1

print("Матрица X:")
print(X)
print(f"\nВектор y: {y.ravel()}")
print(f"λ = {lam}")

I_3 = np.eye(3)
print(f"\nЕдиничная матрица I₃:")
print(I_3)

X_T = X.T
first_part = X_T @ X + lam * I_3
print(f"\nXᵀ·X + λ·I =")
print(first_part.round(4))

inverse_part = np.linalg.inv(first_part)
print(f"\n(Xᵀ·X + λ·I)⁻¹ =")
print(inverse_part.round(4))

theta = inverse_part @ X_T @ y
print(f"\nθ = (Xᵀ·X + λ·I)⁻¹·Xᵀ·y =")
print(theta)

print(f"\nРезультат: θ₁ = {theta[0,0]:.4f}, θ₂ = {theta[1,0]:.4f}, θ₃ = {theta[2,0]:.4f}")

Матрица X:
[[-3  4  1]
 [ 4  3  1]]

Вектор y: [10 12]
λ = 0.1

Единичная матрица I₃:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Xᵀ·X + λ·I =
[[25.1  0.   1. ]
 [ 0.  25.1  7. ]
 [ 1.   7.   2.1]]

(Xᵀ·X + λ·I)⁻¹ =
[[ 0.0545  0.1029 -0.369 ]
 [ 0.1029  0.7602 -2.583 ]
 [-0.369  -2.583   9.262 ]]

θ = (Xᵀ·X + λ·I)⁻¹·Xᵀ·y =
[[0.68478852]
 [2.80148778]
 [0.81180812]]

Результат: θ₁ = 0.6848, θ₂ = 2.8015, θ₃ = 0.8118


№10 (2 балла) Напишите программу, которая будет решать систему линейных уравнений вида:

In [16]:
import numpy as np

print("Система вида:")
print("a11·x + a12·y = b1")
print("a21·x + a22·y = b2")
print()

print("\nПример 1: Система с единственным решением")
print("2x + 3y = 8")
print("3x + 4y = 11")

A1 = np.array([[2, 3], [3, 4]])
B1 = np.array([8, 11])
det1 = np.linalg.det(A1)
print(f"Определитель: {det1}")

if abs(det1) > 1e-10:
    solution1 = np.linalg.solve(A1, B1)
    print(f"Решение: x = {solution1[0]}, y = {solution1[1]}")
else:
    print("Система не имеет решения или имеет бесконечно много решений")

print()
print("Пример 2: Система без решения (определитель = 0)")
print("2x + 4y = 8")
print("1x + 2y = 5")

A2 = np.array([[2, 4], [1, 2]])
B2 = np.array([8, 5])
det2 = np.linalg.det(A2)
print(f"Определитель: {det2}")

if abs(det2) > 1e-10:
    solution2 = np.linalg.solve(A2, B2)
    print(f"Решение: x = {solution2[0]}, y = {solution2[1]}")
else:
    print("Определитель равен 0 → система не имеет решения или имеет бесконечно много решений")

print()
print("Интерактивный режим (введите свои коэффициенты):")
print()

try:
    a11 = float(input("Введите a11: "))
    a12 = float(input("Введите a12: "))
    b1 = float(input("Введите b1: "))
    a21 = float(input("Введите a21: "))
    a22 = float(input("Введите a22: "))
    b2 = float(input("Введите b2: "))
    
    A = np.array([[a11, a12], [a21, a22]])
    B = np.array([b1, b2])
    det = np.linalg.det(A)
    
    if abs(det) < 1e-10:
        print("\nОпределитель = 0 → система не имеет решения или имеет бесконечно много решений")
    else:
        solution = np.linalg.solve(A, B)
        print(f"\nРешение: x = {solution[0]:.4f}, y = {solution[1]:.4f}")
except ValueError:
    print("Ошибка ввода")
except KeyboardInterrupt:
    print("\nПрограмма завершена")

Система вида:
a11·x + a12·y = b1
a21·x + a22·y = b2


Пример 1: Система с единственным решением
2x + 3y = 8
3x + 4y = 11
Определитель: -1.0000000000000004
Решение: x = 1.0, y = 2.0

Пример 2: Система без решения (определитель = 0)
2x + 4y = 8
1x + 2y = 5
Определитель: 0.0
Определитель равен 0 → система не имеет решения или имеет бесконечно много решений

Интерактивный режим (введите свои коэффициенты):


Решение: x = -1.0000, y = 2.0000


№11 (2 балла) Используя numpy, без питоновских циклов сконвертируйте цветное изображение в чёрно-белое по формуле

In [17]:
import numpy as np
from PIL import Image

def bw_convert(input_path='input_image.jpg', output_path='output_bw.jpg'):
    try:
        image = Image.open(input_path)
        print(f"Исходное изображение: {image.size}, {image.mode}")
        
        img_array = np.array(image)
        
        if len(img_array.shape) != 3 or img_array.shape[2] != 3:
            print("Ошибка: изображение не в формате RGB")
            return False
        
        R = img_array[:, :, 0].astype(float)
        G = img_array[:, :, 1].astype(float)
        B = img_array[:, :, 2].astype(float)
        
        gray = 0.2989 * R + 0.5870 * G + 0.1140 * B
        
        gray = np.round(gray).astype(np.uint8)
        
        result_image = Image.fromarray(gray, mode='L')
        result_image.save(output_path)
        
        print(f"Черно-белое изображение сохранено как {output_path}")
        print(f"Размер: {result_image.size}, режим: {result_image.mode}")
        return True
        
    except FileNotFoundError:
        print(f"Ошибка: файл {input_path} не найден")
        print("Создаю тестовое изображение для демонстрации...")
        
        test_img = Image.new('RGB', (400, 300), color='red')
        test_img.save(input_path)
        print(f"Создан тестовый файл {input_path}")
        return bw_convert(input_path, output_path)

bw_convert()

Ошибка: файл input_image.jpg не найден
Создаю тестовое изображение для демонстрации...
Создан тестовый файл input_image.jpg
Исходное изображение: (400, 300), RGB
Черно-белое изображение сохранено как output_bw.jpg
Размер: (400, 300), режим: L


True

№12 (2 балла) В материалах к лабораторной работе лежит файл ABBREV.csv. Это текстовый файл в кодировке UTF-8, в котором записана таблица данных, а данные в строчках разделены символом «точка с запятой».

Файл создан департаментом сельского хозяйства США, и в нём указаны продукты и содержание в них некоторых витаминов, минералов, а также калорийность на единицу массы.

Для чтения данных из этого файла в объект numpy.ndarray воспользуйтесь методом genfromtxt():

In [21]:
import numpy as np

try:
    table = np.genfromtxt('ABBREV.csv', delimiter=';', dtype=None, 
                          names=True, encoding='utf8', filling_values=0)
    
    print(f"Загружено {len(table)} продуктов")
    print(f"Доступные столбцы: {list(table.dtype.names)[:10]}...") 
    
    all_columns = list(table.dtype.names)
    
    calories_col = None
    sugar_col = None
    protein_col = None
    vitc_col = None
    name_col = None
    
    for col in all_columns:
        if 'Kcal' in col:
            calories_col = col
        if 'Sugar' in col:
            sugar_col = col
        if 'Protein' in col:
            protein_col = col
        if 'Vit_C' in col:
            vitc_col = col
        if 'Shrt_Desc' in col or 'Desc' in col:
            name_col = col
    
    print(f"\nНайденные столбцы:")
    print(f"  Калории: {calories_col}")
    print(f"  Сахар: {sugar_col}")
    print(f"  Белок: {protein_col}")
    print(f"  Витамин C: {vitc_col}")
    print(f"  Название: {name_col}")
    
    print("\n" + "-" * 50)
    max_calories = np.max(table[calories_col])
    max_calorie_foods = table[table[calories_col] == max_calories]
    max_calorie_names = max_calorie_foods[name_col]
    max_calorie_food = np.sort(max_calorie_names)[-1] if len(max_calorie_names) > 0 else max_calorie_names[0]
    print(f"★ Самый калорийный продукт:")
    print(f"   Название: {max_calorie_food}")
    print(f"   Калорийность: {max_calories} ккал")
    
    print("\n" + "-" * 50)
    if sugar_col:
        sugar_data = table[sugar_col]
        sugar_data_clean = np.where(np.isnan(sugar_data), np.inf, sugar_data)
        valid_sugar = sugar_data_clean < 1e10
        if np.any(valid_sugar):
            min_sugar = np.min(sugar_data_clean[valid_sugar])
            min_sugar_foods = table[(sugar_data_clean == min_sugar) & valid_sugar]
            min_sugar_names = min_sugar_foods[name_col]
            min_sugar_food = np.sort(min_sugar_names)[0] if len(min_sugar_names) > 0 else min_sugar_names[0]
            print(f"★ Самый полезный (минимальный сахар):")
            print(f"   Название: {min_sugar_food}")
            print(f"   Содержание сахара: {min_sugar} г")
    
    print("\n" + "-" * 50)
    if protein_col:
        max_protein = np.max(table[protein_col])
        max_protein_foods = table[table[protein_col] == max_protein]
        max_protein_names = max_protein_foods[name_col]
        max_protein_food = np.sort(max_protein_names)[0] if len(max_protein_names) > 0 else max_protein_names[0]
        print(f"★ Самый богатый белком продукт:")
        print(f"   Название: {max_protein_food}")
        print(f"   Содержание белка: {max_protein} г")
    
    print("\n" + "-" * 50)
    if vitc_col:
        vit_c_data = table[vitc_col]
        vit_c_data_clean = np.where(np.isnan(vit_c_data), -np.inf, vit_c_data)
        valid_vit_c = vit_c_data_clean > -1e10
        if np.any(valid_vit_c):
            max_vit_c = np.max(vit_c_data_clean[valid_vit_c])
            vit_c_foods = table[(vit_c_data_clean == max_vit_c) & valid_vit_c]
            if len(vit_c_foods) > 0:
                vit_c_food = vit_c_foods[name_col][0]
                print(f"★ Самый богатый витамином C продукт:")
                print(f"   Название: {vit_c_food}")
                print(f"   Содержание витамина C: {max_vit_c} мг")
    
except FileNotFoundError:
    print("Ошибка: файл ABBREV.csv не найден")
    print("Убедитесь, что файл находится в той же папке, что и программа")
except Exception as e:
    print(f"Ошибка при обработке файла: {e}")
    print("\nПопробуем вывести названия всех столбцов для отладки:")
    try:
        with open('ABBREV.csv', 'r', encoding='utf8') as f:
            first_line = f.readline().strip()
            columns = first_line.split(';')
            print("Столбцы в файле:")
            for i, col in enumerate(columns):
                print(f"  {i}: '{col}'")
    except:
        pass

Загружено 8790 продуктов
Доступные столбцы: ['NDB_No', 'Shrt_Desc', 'Water_g', 'Energ_Kcal', 'Protein_g', 'Lipid_Tot_g', 'Ash_g', 'Carbohydrt_g', 'Fiber_TD_g', 'Sugar_Tot_g']...

Найденные столбцы:
  Калории: Energ_Kcal
  Сахар: Sugar_Tot_g
  Белок: Protein_g
  Витамин C: Vit_C_mg
  Название: GmWt_Desc2

--------------------------------------------------
★ Самый калорийный продукт:
   Название: 1 tsp
   Калорийность: 902 ккал

--------------------------------------------------
★ Самый полезный (минимальный сахар):
   Название: ".5 fruit.  (3-3/4"" dia)"
   Содержание сахара: 0.0 г

--------------------------------------------------
★ Самый богатый белком продукт:
   Название: 0
   Содержание белка: 88.32 г

--------------------------------------------------
★ Самый богатый витамином C продукт:
   Название: 0
   Содержание витамина C: 2732.0 мг


№13 (1 балл) У вас есть некоторый файл lines.txt, состоящий из нескольких строк.

Вам необходимо вывести на экран случайную строку из этого файла. Файл может быть пустым, тогда и выводить ничего не надо.

In [ ]:
import random

test_filename = 'lines.txt'
try:
    with open(test_filename, 'r', encoding='utf-8') as file:
        lines = file.readlines()
except FileNotFoundError:
    print(f"Файл {test_filename} не найден, создие тестового...")
    test_lines = [
        "Первая строка файла\n",
        "Вторая строка файла\n", 
        "Третья строка файла\n",
        "Четвертая строка файла\n",
        "Пятая строка файла\n"
    ]
    with open(test_filename, 'w', encoding='utf-8') as f:
        f.writelines(test_lines)
    print(f"Создан файл {test_filename} с {len(test_lines)} строками")
    with open(test_filename, 'r', encoding='utf-8') as file:
        lines = file.readlines()

if lines:
    random_line = random.choice(lines).strip()
    print(f"\nСлучайная строка из файла:")
    print(f"{random_line:<48} ")

else:
    print("Файл пуст, выводить ничего не надо")


Случайная строка из файла:
Пятая строка файла                               


№14 (1 балл) Напишите функцию reverse(), которая побайтно читает бинарные данные из файла input.dat и создает файл output.dat, куда сохраняет прочитанные данные в обратном порядке.

Постарайтесь решить эту задачу без использования циклов.

In [ ]:
def reverse():

    try:
        with open('input.dat', 'rb') as infile:
            data = infile.read()
        
        reversed_data = data[::-1]
        
        with open('output.dat', 'wb') as outfile:
            outfile.write(reversed_data)
        
        return True
    except FileNotFoundError:
        print("Файл input.dat не найден")
        return False

test_data = b'Hello, World! This is a test file.'
with open('input.dat', 'wb') as f:
    f.write(test_data)

print(f"Исходные данные: {test_data}")
print(f"Длина: {len(test_data)} байт")

if reverse():
    with open('output.dat', 'rb') as f:
        result = f.read()
    print(f"\nРезультат: {result}")
    print(f"Обратный порядок: {result == test_data[::-1]}")

Исходные данные: b'Hello, World! This is a test file.'
Длина: 34 байт

Результат: b'.elif tset a si sihT !dlroW ,olleH'
Обратный порядок: True


№15 (1 балл) В текстовом файле input.txt через пробельные символы (пробел, табуляция, перевод строки и т.д.) записаны целые числа — данные, полученные с некоторого устройства. Количество их неизвестно.

In [28]:
import re

test_content = "1 -1 2 -2 0 4 9 100 8"
with open('input.txt', 'w', encoding='utf-8') as f:
    f.write(test_content)

print(f"Содержимое input.txt: {test_content}")

with open('input.txt', 'r', encoding='utf-8') as f:
    content = f.read()

numbers = list(map(int, re.findall(r'-?\d+', content)))

print(f"\nНайденные числа: {numbers}")
print(f"Всего чисел: {len(numbers)}")

positive = [n for n in numbers if n > 0]
negative = [n for n in numbers if n < 0]
zero = [n for n in numbers if n == 0]

print(f"Положительных: {len(positive)}")
print(f"Отрицательных: {len(negative)}")
print(f"Нулей: {len(zero)}")

with open('output.txt', 'w', encoding='utf-8') as f:
    f.write(f"{len(numbers)}\n")
    
    result_parts = []
    if positive:
        result_parts.extend(['1', str(len(positive))])
    if negative:
        result_parts.extend(['-1', str(len(negative))])
    if zero:
        result_parts.extend(['0', str(len(zero))])
    
    output = ' '.join(result_parts)
    f.write(output)

print(f"\nРезультат сохранен в output.txt:")
print(f"Строка 1: {len(numbers)}")
print(f"Строка 2: {output}")

print("\n" + "-" * 50)
print("Проверка с примером 1:")
example1 = "1 -1 2 -2 0 4 9 100 8"
print(f"Ввод: {example1}")
print("Ожидаемый вывод:")
print("9")
print("1 5 -1 2 0 1")

Содержимое input.txt: 1 -1 2 -2 0 4 9 100 8

Найденные числа: [1, -1, 2, -2, 0, 4, 9, 100, 8]
Всего чисел: 9
Положительных: 6
Отрицательных: 2
Нулей: 1

Результат сохранен в output.txt:
Строка 1: 9
Строка 2: 1 6 -1 2 0 1

--------------------------------------------------
Проверка с примером 1:
Ввод: 1 -1 2 -2 0 4 9 100 8
Ожидаемый вывод:
9
1 5 -1 2 0 1


№16 (2 балла) На вход программе подается BMP-файл, содержащий некоторое изображение. Без использования сторонних графических библиотек (например, PIL) сформируйте новый файл, в который сохраните негатив, полученный из исходного изображения.

№17 (1 балл) В csv-файле хранится информация о продуктах: название, старая и новая цены. Цены указаны в копейках.

Выведите на экран в порядке упоминания в файле те товары, цена на которые уменьшилась.

Если товаров, попадающих под условие задачи, нет, то на экран выводить ничего не надо.

Для быстрого решения задачи воспользуйтесь объектом DictReader.

In [32]:
import csv
import os

test_file = 'prices.csv'
test_data = [
    ['name', 'old_price', 'new_price'],
    ['Товар А', '10000', '9000'],
    ['Товар Б', '5000', '5500'], 
    ['Товар В', '3000', '3000'], 
    ['Товар Г', '20000', '15000'],
    ['Товар Д', '8000', '8000']
]

if not os.path.exists(test_file):
    with open(test_file, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerows(test_data)
    print(f"Создан тестовый файл {test_file}")

print("\nТовары с уменьшившейся ценой:")
print("-" * 40)

found = False
with open(test_file, 'r', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    for row in reader:
        old_price = int(row['old_price'])
        new_price = int(row['new_price'])
        if new_price < old_price:
            print(f"  {row['name']}: {old_price} коп → {new_price} коп")
            found = True

if not found:
    print("  Нет товаров с уменьшившейся ценой")


Товары с уменьшившейся ценой:
----------------------------------------
  Товар А: 10000 коп → 9000 коп
  Товар Г: 20000 коп → 15000 коп


№18 (2 балла) В файле rez.csv содержатся результаты олимпиады: Т.е. место, имя участника, логин, названия четырех задач и сумма баллов.

Поля отделяются запятой. Каждая запись об участнике находится в отдельной строке.

Логин участника имеет вид sh-kaluga16-**-#@, где ** — номер школы, а ## — номер класса, @ — номер участника. Определите результаты олимпиады для указанной школы и класса.

Ваша программа должна вывести имена всех участников и балл через пробел из данной школы и класса в порядке убывания балла. При совпадении баллов фамилии нужно выводить в обратном алфавитном порядке. Информацию о каждом участнике надо выводить с новой строки.

In [35]:
import csv

def olympiad_results(school, grade, filename='rez.csv'):
    results = []
    
    try:
        with open(filename, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                login = row['login']
                if login and login.startswith('sh-kaluga16-'):
                    parts = login.split('-')
                    if len(parts) >= 5:
                        school_num = parts[2]
                        class_num = parts[3]
                        
                        if school_num == school and class_num == grade:
                            name = row['user_name']
                            score = int(row['Score'])
                            results.append((name, score))
        
        if not results:
            print(f"Участники школы {school}, класса {grade} не найдены")
            return
        
        results.sort(key=lambda x: (-x[1], x[0]), reverse=True)
        results.sort(key=lambda x: (-x[1], -ord(x[0][0]) if x[0] else 0))
        
        print(f"\nУчастники школы {school}, класса {grade}:")
        print("-" * 50)
        for name, score in results:
            print(f"{name} {score}")
            
    except FileNotFoundError:
        print(f"Ошибка: файл {filename} не найден")
        print("Создаю тестовый файл...")
        create_test_rez_file()
        olympiad_results(school, grade, filename)

def create_test_rez_file():
    test_data = [
        ['place', 'user_name', 'login', '1(Система счисления)', '2(Количество символов)', '3(Минимальное число)', '4(Трамвай)', 'Score'],
        ['1-4', 'У 09 11 Макеев В', 'sh-kaluga16-09-11-1', '100(+)', '100(+)', '100(+1)', '0(+3)', '300'],
        ['1-4', 'У 01 09 Серокуров Е', 'sh-kaluga16-01-09-1', '100(+2)', '100(+1)', '100(+)', '', '300'],
        ['1-4', 'У 36 11 Паксеваткин А', 'sh-kaluga16-36-11-10', '100(+)', '100(+)', '100(+)', '', '300'],
        ['5', 'У 09 11 Царьклова А', 'sh-kaluga16-09-11-6', '100(+)', '100(+1)', '70(+2)', '0(+1)', '270'],
        ['6-7', 'У 09 11 Лапа Н', 'sh-kaluga16-09-11-2', '100(+1)', '100(+)', '60(+9)', '0(+1)', '260'],
    ]
    
    with open('rez.csv', 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerows(test_data)
    print("Создан тестовый файл rez.csv")


olympiad_results("09", "11")

olympiad_results("01", "09")


Участники школы 09, класса 11:
--------------------------------------------------
У 09 11 Макеев В 300
У 09 11 Царьклова А 270
У 09 11 Лапа Н 260

Участники школы 01, класса 09:
--------------------------------------------------
У 01 09 Серокуров Е 300
У 01 09 Степанов М 100
